# Generated by Django 3.1.5 on 2021-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='additional_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
