# Generated by Django 3.1.5 on 2021-01-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0002_auto_20210123_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='pub_city',
            field=models.CharField(max_length=255, verbose_name='Город издательства'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_name',
            field=models.CharField(max_length=255, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_site',
            field=models.URLField(verbose_name='Сайт издательства'),
        ),
    ]
