# Generated by Django 3.1.5 on 2021-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0007_auto_20210123_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='additional_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
    ]
