# Generated by Django 3.1.5 on 2021-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0008_auto_20210123_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='pub_site',
            field=models.URLField(blank=True, verbose_name='Сайт издательства'),
        ),
    ]
