# Generated by Django 3.1.5 on 2021-01-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0011_auto_20210125_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='small_photo',
            field=models.ImageField(blank=True, default='D:\\learning\\Programming\\skillfactory\\module_D6\\media/books_photo\\no_photo_small.jpg', upload_to='books_photo/small'),
        ),
    ]
