# Generated by Django 3.1.5 on 2021-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0012_auto_20210125_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='small_photo',
            field=models.ImageField(blank=True, default='/media/books_photo\\no_photo_small.jpg', upload_to='books_photo/small'),
        ),
    ]
