# Generated by Django 3.1.5 on 2021-01-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_lib', '0013_auto_20210125_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, default='books_photo\\no_photo.jpg', upload_to='books_photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_photo',
            field=models.ImageField(blank=True, default='books_photo\\no_photo_small.jpg', upload_to='books_photo/small'),
        ),
    ]
